name = "dailyrecord-reminders"
main = "worker.js"
compatibility_date = "2026-09-16"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "REMINDERS"
class_name = "ReminderRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReminderRoom"]
